### ISSUE TITLE
Hide component from header and nav-bar when 'page page-hide-components' is set

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonita-documentation-theme#214]
We need to hide some component entry from header and from navigation explore menu 

![image](https://github.com/bonitasoft/bonita-documentation-theme/assets/25297128/c8bd4f50-dcfa-41a0-82aa-450081fabfac)
![image](https://github.com/bonitasoft/bonita-documentation-theme/assets/25297128/1b6e46d6-05be-476d-8524-6ff32aa595cd)

We could use the  attribute page (based on component configuration file https://github.com/bonitasoft/bonita-documentation-site/issues/689) named `page-hide-components` to do it.

Tasks:

- [x] Create a helper to filter the components array
- [x] Adding a dedicated page on documentation preview site

**Comment by benjaminParisel** [comment]
:warning: With the preview-src file on the documenation-theme project, the `site.components`  give us an Array of components.
When we build the documentation-site project, the `site.components` give us a Object of object.

So we need to to an ugly conversion to avoid some compilation errors.

`FATAL (antora): components.filter is not a function in UI template layouts/default.hbs
    Cause: Error
    ion
        at module.exports (helpers/isComponentToHide.js:7:23)
        at Object.wrapper (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
        at eval (eval at createFunctionContext (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:10:197)
        at Object.prog [as inverse] (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
        at Object.<anonymous> (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:27:22)
        at Object.<anonymous> (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:37:35)
        at Object.wrapper (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
        at Object.eval [as main] (eval at createFunctionContext (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:17:51)
        at main (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
        at ret (/mnt/SharedVolume/worskpace/doc/bonita-documentation-site/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
`
